# Generated by Django 4.0.4 on 2022-05-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_blogcomments_blogcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
