# Generated by Django 4.0.4 on 2022-05-11 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComments',
            new_name='BlogComment',
        ),
        migrations.RenameModel(
            old_name='BlogTags',
            new_name='BlogTag',
        ),
    ]
